//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool. Changes will be lost if regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Microsoft.Win32;

namespace GeneratedCode
{
    // Generated: uses Registry, but must NOT be flagged (migration regenerates this).
    internal static class Reference
    {
        public static object Read() => Registry.LocalMachine.OpenSubKey("SOFTWARE\\Contoso");
    }
}
